language: cpp
sudo: required
dist: trusty

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
    include:
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
          sources:
            - ubuntu-toolchain-r-test
        sonarqube:
          organization: "travis"

      env:
        - C_COMPILER=clang-3.8 CXX_COMPILER=clang++-3.8
        - BUILD_TYPE=debug

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y gdb

before_script:
  - ulimit -c unlimited -S # enable core dumps
  - sudo bash -c "echo 'core.%p.%E' > /proc/sys/kernel/core_pattern"

script:
  - mkdir build
  - cd build
  - CC=${C_COMPILER} CXX=${CXX_COMPILER} cmake -DCMAKE_BUILD_TYPE=${BUILD_TYPE} ..
  - make -j2 VERBOSE=1
  - ./travis
  - ./travis
  - ./travis
  - cd ..
  - sonar-scanner

after_failure:
  - ls
  - ls build/
  - ls build/core
  - COREFILE=$(find build/ -maxdepth 1 -name "core.*")
  - echo ${COREFILE}
  - for binname in $(echo ${COREFILE}); do gdb -c ${binname} $(echo ${binname}|cut -d "." -f 3|tr \! \/) -ex "thread apply all bt" -ex "set pagination 0" -batch; done

notifications:
  email: false
